# Generated by Django 4.0.6 on 2023-07-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_api', '0002_myfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
